# Generated by Django 4.0 on 2022-01-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0002_item_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imgurl',
        ),
    ]
