# Generated by Django 4.0 on 2022-01-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0003_remove_item_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calorias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='imglink',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
