# Generated by Django 4.0 on 2022-01-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0004_item_calorias_item_imglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='calorias',
        ),
        migrations.AlterField(
            model_name='item',
            name='imglink',
            field=models.CharField(max_length=200),
        ),
    ]
