# Generated by Django 4.0 on 2022-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0005_remove_item_calorias_alter_item_imglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
